[package]
name = "sonora-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sonora-common.workspace = true
sonora-dsp.workspace = true
sonora-audio.workspace = true
sonora-library.workspace = true
sonora-lyrics.workspace = true
sonora-plugin.workspace = true
sonora-registry.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
