/**
 * Built-in Theme Presets and Accent Color Palettes.
 */

import { type ThemeDefinition, THEME_SCHEMA_URI } from './schema.ts';

export interface AccentColorPreset {
  id: string;
  name: string;
  hex: string;
}

export const ACCENT_COLOR_PRESETS: AccentColorPreset[] = [
  { id: 'indigo', name: 'Studio Indigo', hex: '#6366f1' },
  { id: 'violet', name: 'Electric Violet', hex: '#8b5cf6' },
  { id: 'rose', name: 'Velvet Rose', hex: '#f43f5e' },
  { id: 'amber', name: 'Warm Amber', hex: '#f59e0b' },
  { id: 'emerald', name: 'Lush Emerald', hex: '#10b981' },
  { id: 'cyan', name: 'Neon Cyan', hex: '#06b6d4' },
  { id: 'cobalt', name: 'Pure Cobalt', hex: '#2563eb' },
];

export const THEME_DEFAULT_DARK: ThemeDefinition = {
  $schema: THEME_SCHEMA_URI,
  id: 'sonora-default-dark',
  name: 'Sonora Studio (Dark)',
  description: 'Default balanced dark theme with high-contrast slate and vibrant indigo accents.',
  version: '1.0.0',
  author: 'Sonora Team',
  mode: 'dark',
  isBuiltIn: true,
  tokens: {
    '--bg-base': '#0c0d11',
    '--bg-surface': '#14161d',
    '--bg-surface-hover': '#191c25',
    '--bg-elevated': '#1b1e28',
    '--bg-card': '#161922',
    '--bg-card-hover': '#222634',
    '--bg-active': '#282d3d',
    '--bg-glass': 'rgba(20, 22, 29, 0.85)',
    '--accent-primary': '#6366f1',
    '--accent-primary-hover': '#4f46e5',
    '--accent-primary-active': '#4338ca',
    '--accent-secondary': '#a855f7',
    '--accent-secondary-hover': '#9333ea',
    '--accent-glow': 'rgba(99, 102, 241, 0.25)',
    '--accent-subtle': 'rgba(99, 102, 241, 0.12)',
    '--text-primary': '#f8fafc',
    '--text-secondary': '#94a3b8',
    '--text-muted': '#64748b',
    '--text-disabled': '#475569',
    '--text-inverse': '#0f172a',
    '--border-subtle': '#242936',
    '--border-medium': '#333a4c',
    '--border-focus': '#6366f1',
    '--border-active': '#818cf8',
    '--state-success': '#10b981',
    '--state-warning': '#f59e0b',
    '--state-danger': '#ef4444',
    '--state-info': '#3b82f6',
    '--glow-intensity': '0.6',
  },
};

export const THEME_OLED_OBSIDIAN: ThemeDefinition = {
  $schema: THEME_SCHEMA_URI,
  id: 'sonora-oled-obsidian',
  name: 'OLED Obsidian',
  description: 'Pure pitch-black background with ultra-deep contrast designed for OLED displays.',
  version: '1.0.0',
  author: 'Sonora Team',
  mode: 'dark',
  isBuiltIn: true,
  tokens: {
    '--bg-base': '#000000',
    '--bg-surface': '#090a0d',
    '--bg-surface-hover': '#12141a',
    '--bg-elevated': '#161820',
    '--bg-card': '#0c0d12',
    '--bg-card-hover': '#181b24',
    '--bg-active': '#1e2230',
    '--bg-glass': 'rgba(9, 10, 13, 0.92)',
    '--accent-primary': '#8b5cf6',
    '--accent-primary-hover': '#7c3aed',
    '--accent-primary-active': '#6d28d9',
    '--accent-secondary': '#ec4899',
    '--accent-secondary-hover': '#db2777',
    '--accent-glow': 'rgba(139, 92, 246, 0.35)',
    '--accent-subtle': 'rgba(139, 92, 246, 0.15)',
    '--text-primary': '#ffffff',
    '--text-secondary': '#a1a1aa',
    '--text-muted': '#71717a',
    '--text-disabled': '#3f3f46',
    '--text-inverse': '#000000',
    '--border-subtle': '#181920',
    '--border-medium': '#272935',
    '--border-focus': '#8b5cf6',
    '--border-active': '#a78bfa',
    '--state-success': '#10b981',
    '--state-warning': '#f59e0b',
    '--state-danger': '#ef4444',
    '--state-info': '#3b82f6',
    '--glow-intensity': '0.7',
  },
};

export const THEME_CYBERPUNK_NEON: ThemeDefinition = {
  $schema: THEME_SCHEMA_URI,
  id: 'sonora-cyberpunk-neon',
  name: 'Cyberpunk Neon',
  description: 'Luminous cyan, electric magenta, and high-energy neon night aesthetics.',
  version: '1.0.0',
  author: 'Sonora Team',
  mode: 'dark',
  isBuiltIn: true,
  tokens: {
    '--bg-base': '#08090d',
    '--bg-surface': '#10121a',
    '--bg-surface-hover': '#161926',
    '--bg-elevated': '#1d2133',
    '--bg-card': '#121420',
    '--bg-card-hover': '#1e2236',
    '--bg-active': '#262c44',
    '--bg-glass': 'rgba(16, 18, 26, 0.88)',
    '--accent-primary': '#00f2fe',
    '--accent-primary-hover': '#00c6d4',
    '--accent-primary-active': '#009ba6',
    '--accent-secondary': '#f355da',
    '--accent-secondary-hover': '#d93abf',
    '--accent-glow': 'rgba(0, 242, 254, 0.35)',
    '--accent-subtle': 'rgba(0, 242, 254, 0.14)',
    '--text-primary': '#f0fdfa',
    '--text-secondary': '#99f6e4',
    '--text-muted': '#5eead4',
    '--text-disabled': '#2dd4bf',
    '--text-inverse': '#042f2e',
    '--border-subtle': '#1a2233',
    '--border-medium': '#273550',
    '--border-focus': '#00f2fe',
    '--border-active': '#f355da',
    '--state-success': '#00f2fe',
    '--state-warning': '#facc15',
    '--state-danger': '#ff0055',
    '--state-info': '#38bdf8',
    '--glow-intensity': '0.9',
  },
};

export const THEME_NORD_FROST: ThemeDefinition = {
  $schema: THEME_SCHEMA_URI,
  id: 'sonora-nord-frost',
  name: 'Nord Frost',
  description: 'An arctic, north-bluish clean dark palette based on the Nord design system.',
  version: '1.0.0',
  author: 'Sonora Team',
  mode: 'dark',
  isBuiltIn: true,
  tokens: {
    '--bg-base': '#242933',
    '--bg-surface': '#2e3440',
    '--bg-surface-hover': '#3b4252',
    '--bg-elevated': '#434c5e',
    '--bg-card': '#2e3440',
    '--bg-card-hover': '#3b4252',
    '--bg-active': '#4c566a',
    '--bg-glass': 'rgba(46, 52, 64, 0.88)',
    '--accent-primary': '#88c0d0',
    '--accent-primary-hover': '#81a1c1',
    '--accent-primary-active': '#5e81ac',
    '--accent-secondary': '#b48ead',
    '--accent-secondary-hover': '#987591',
    '--accent-glow': 'rgba(136, 192, 208, 0.28)',
    '--accent-subtle': 'rgba(136, 192, 208, 0.14)',
    '--text-primary': '#eceff4',
    '--text-secondary': '#e5e9f0',
    '--text-muted': '#d8dee9',
    '--text-disabled': '#4c566a',
    '--text-inverse': '#2e3440',
    '--border-subtle': '#3b4252',
    '--border-medium': '#434c5e',
    '--border-focus': '#88c0d0',
    '--border-active': '#81a1c1',
    '--state-success': '#a3be8c',
    '--state-warning': '#ebcb8b',
    '--state-danger': '#bf616a',
    '--state-info': '#88c0d0',
    '--glow-intensity': '0.5',
  },
};

export const THEME_NORDIC_DAY: ThemeDefinition = {
  $schema: THEME_SCHEMA_URI,
  id: 'sonora-nordic-day',
  name: 'Nordic Day (Light)',
  description: 'Clean, radiant Scandinavian light theme with crisp contrast and cobalt accents.',
  version: '1.0.0',
  author: 'Sonora Team',
  mode: 'light',
  isBuiltIn: true,
  tokens: {
    '--bg-base': '#f1f5f9',
    '--bg-surface': '#ffffff',
    '--bg-surface-hover': '#f8fafc',
    '--bg-elevated': '#ffffff',
    '--bg-card': '#ffffff',
    '--bg-card-hover': '#f8fafc',
    '--bg-active': '#e2e8f0',
    '--bg-glass': 'rgba(255, 255, 255, 0.90)',
    '--accent-primary': '#2563eb',
    '--accent-primary-hover': '#1d4ed8',
    '--accent-primary-active': '#1e40af',
    '--accent-secondary': '#7c3aed',
    '--accent-secondary-hover': '#6d28d9',
    '--accent-glow': 'rgba(37, 99, 235, 0.20)',
    '--accent-subtle': 'rgba(37, 99, 235, 0.08)',
    '--text-primary': '#0f172a',
    '--text-secondary': '#334155',
    '--text-muted': '#64748b',
    '--text-disabled': '#94a3b8',
    '--text-inverse': '#ffffff',
    '--border-subtle': '#e2e8f0',
    '--border-medium': '#cbd5e1',
    '--border-focus': '#2563eb',
    '--border-active': '#3b82f6',
    '--state-success': '#059669',
    '--state-warning': '#d97706',
    '--state-danger': '#dc2626',
    '--state-info': '#2563eb',
    '--glow-intensity': '0.3',
  },
};

export const THEME_SOLARIZED_LIGHT: ThemeDefinition = {
  $schema: THEME_SCHEMA_URI,
  id: 'sonora-solarized-light',
  name: 'Solarized Warm (Light)',
  description: 'Warm parchment tones engineered for reduced eye strain during extended daytime listening.',
  version: '1.0.0',
  author: 'Sonora Team',
  mode: 'light',
  isBuiltIn: true,
  tokens: {
    '--bg-base': '#fdf6e3',
    '--bg-surface': '#eee8d5',
    '--bg-surface-hover': '#e4dcc7',
    '--bg-elevated': '#fbf1c7',
    '--bg-card': '#f5eedb',
    '--bg-card-hover': '#ede3cc',
    '--bg-active': '#dcd3be',
    '--bg-glass': 'rgba(238, 232, 213, 0.92)',
    '--accent-primary': '#b58900',
    '--accent-primary-hover': '#987100',
    '--accent-primary-active': '#7d5c00',
    '--accent-secondary': '#2aa198',
    '--accent-secondary-hover': '#21847c',
    '--accent-glow': 'rgba(181, 137, 0, 0.25)',
    '--accent-subtle': 'rgba(181, 137, 0, 0.10)',
    '--text-primary': '#073642',
    '--text-secondary': '#586e75',
    '--text-muted': '#657b83',
    '--text-disabled': '#93a1a1',
    '--text-inverse': '#fdf6e3',
    '--border-subtle': '#dcd3be',
    '--border-medium': '#cbbfab',
    '--border-focus': '#b58900',
    '--border-active': '#2aa198',
    '--state-success': '#859900',
    '--state-warning': '#cb4b16',
    '--state-danger': '#dc322f',
    '--state-info': '#268bd2',
    '--glow-intensity': '0.35',
  },
};

export const BUILT_IN_THEMES: ThemeDefinition[] = [
  THEME_DEFAULT_DARK,
  THEME_OLED_OBSIDIAN,
  THEME_CYBERPUNK_NEON,
  THEME_NORD_FROST,
  THEME_NORDIC_DAY,
  THEME_SOLARIZED_LIGHT,
];
