[package]
name = "sonora-library"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sonora-common.workspace = true
rusqlite.workspace = true
lofty.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
image.workspace = true
sonora-lyrics.workspace = true
