[package]
name = "sonora-lyrics"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
sonora-common.workspace = true
serde.workspace = true
tracing.workspace = true
lofty.workspace = true
reqwest = { version = "0.13", features = ["json", "blocking", "query"] }
